version: "3.9"

services:
  knskn:
    build: .
    environment:
      - DEBUG=1

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"